# count-action-users: Generates Shields endpoint with number of users of a GitHub Action
# 
# Copyright (c) 2021 Vincent A Cicirello
# https://www.cicirello.org/
#
# MIT License
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 
name: 'count-action-users'
description: 'Generates Shields endpoint with number of users of a GitHub Action'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  action-list:  
    description: 'Comma or space separated list of GitHub Actions'
    required: true
  target-directory:
    description: 'Target directory relative to repository root where the endpoints should be stored'
    required: false
    default: '' # Default of empty string defaults to root
  fail-on-error:
    description: 'Choose whether to fail the workflow if there is an error'
    required: false
    default: true
  commit-and-push:
    description: 'Commits and pushes the generated endpoints'
    required: false
    default: true
  color:
    description: 'The color for the right side of the badge'
    required: false
    default: '#4c1' # A bright shade of green
  include-logo:
    description: 'If true will include a named logo on the left'
    required: false
    default: true
  named-logo:
    description: 'The name of a logo supported by shields or simple-icons'
    required: false
    default: githubactions # Defaults to the GitHub Actions logo
  style:
    description: 'One of the styles supported by Shields.io.'
    required: false
    default: flat # This is Shield's default style
outputs:
  exit-code:
    description: '0 if successful or non-zero if unsuccessful'	
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action-list }}
    - ${{ inputs.target-directory }}
    - ${{ inputs.fail-on-error }}
    - ${{ inputs.commit-and-push }}
    - ${{ inputs.color }}
    - ${{ inputs.include-logo }}
    - ${{ inputs.named-logo }}
    - ${{ inputs.style }}
