name: samples

on:
  push:
    branches: [ main ]
    paths: [ '.github/workflows/generate-samples.yml' ]
  workflow_dispatch:

jobs:
  samples:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
      with:
        ref: samples

    - name: Generate the samples
      uses: cicirello/count-action-users@main
      with:
        action-list: >
          cicirello/jacoco-badge-generator
          actions/setup-python
          actions/checkout
        target-directory: endpoints
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
